### ISSUE TITLE
won't compile with gcc 10.2 

### ISSUE THREAD

**Issue by 001Tycoon** [Zabrimus/vdr-plugin-hbbtv#6]
Hello
hbbtv won't compile with gcc 10.2.0
gcc 9.3.0 is fine

x86_64-pc-linux-gnu-9.3.0
x86_64-pc-linux-gnu-10.2.0

*** Plugin hbbtv:
`c++ -g -O3 -Wall -Werror=overloaded-virtual -Wno-parentheses  -fPIC -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE  -c -DPLUGIN_NAME_I18N='"hbbtv"' -I/usr/local/src/vdr-git/include -Ithirdparty/nng-1.2.6/include/nng/compat -o status.o status.c
In file included from status.c:13:
browsercommunication.h:33:26: error: ‘string’ is not a member of ‘std’
   33 |     std::map<eKeys, std::string> keyMapping;
      |                          ^~~~~~
browsercommunication.h:10:1: note: ‘std::string’ is defined in header ‘<string>’; did you forget to ‘#include <string>’?
    9 | #include <vdr/keys.h>
  +++ |+#include <string>
   10 |
browsercommunication.h:33:26: error: ‘string’ is not a member of ‘std’
   33 |     std::map<eKeys, std::string> keyMapping;
      |                          ^~~~~~
browsercommunication.h:33:26: note: ‘std::string’ is defined in header ‘<string>’; did you forget to ‘#include <string>’?
browsercommunication.h:33:32: error: template argument 2 is invalid
   33 |     std::map<eKeys, std::string> keyMapping;
      |                                ^
browsercommunication.h:33:32: error: template argument 4 is invalid
browsercommunication.h:51:23: error: ‘std::string’ has not been declared
   51 |     bool SendKey(std::string key);
      |                       ^~~~~~
status.c: In member function ‘virtual void cHbbtvDeviceStatus::ChannelSwitch(const cDevice*, int, bool)’:
status.c:64:18: warning: ignoring return value of ‘int asprintf(char**, const char*, ...)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
   64 |          asprintf(&search, "%s~~~", currentChannel);
      |          ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[1]: *** [Makefile:77: status.o] Error 1
`

**Comment by Zabrimus** [comment]
Thanks. Should be fixed with the last commit.

**Comment by 001Tycoon** [comment]
Thanks works
